### ISSUE TITLE
use native stuff

### ISSUE THREAD

**Issue by jimmywarting** [Pandora-Protocol/pandora-protocol-reference#1]
like
- native async / await
- asyncIterator
- Iterator
- Function generators (iterator)

**Comment by ibudisteanu** [comment]
Hi @jimmywarting! Thanks for reaching out. The kademlia protocol and all network related will not use native async/await and use only native callbacks to improve the speed of the core functionality. We aim for the research project to target 20 million network nodes in a research study only. Minor features that will not impact the network will be implemented with promises.

I am not so sure if asyncIterator and Iterators are very fast?

**Comment by jimmywarting** [comment]
Do as you wish
