### ISSUE TITLE
You are mixing whatwg streams with node streams

### ISSUE THREAD

**Issue by jimmywarting** [Pandora-Protocol/pandora-protocol-reference#2]
https://github.com/Pandora-Protocol/pandora-protocol-reference/blob/d97aa8f18615f758c1a00baa80f145f1e4948368/src/pandora-locations/browser/browser-pandora-locations.js#L163-L169

the end in `mystream.end()` indicates to me that this is a node stream. Conflux don't accept a node stream

You have to convert that to a whatwg ReadableStream somehow

**Comment by ibudisteanu** [comment]
Any idea how to do that? We don't have any knowledge about nodejs' streams. First time I used them more than reading/writing files.

**Comment by jimmywarting** [comment]
https://www.npmjs.com/package/web-streams-node
