### ISSUE TITLE
Move the pipeTo

### ISSUE THREAD

**Issue by jimmywarting** [Pandora-Protocol/pandora-protocol-reference#3]
Move this up:

https://github.com/Pandora-Protocol/pandora-protocol-reference/blob/d97aa8f18615f758c1a00baa80f145f1e4948368/src/pandora-locations/browser/browser-pandora-locations.js#L181

so it becomes:

        const streamer = streamsaver.createWriteStream( name + '.zip', )
        const { readable, writable } = new Writer();
        readable.pipeTo(streamer);
        const writer = writable.getWriter();

**Comment by ibudisteanu** [comment]
Thanks for the tip! I did, but still, I get the same error.

https://github.com/Pandora-Protocol/pandora-protocol-reference/commit/8a772e6da005ad40ab703d54167370d1c5c27c87
