### ISSUE TITLE
is size correct?

### ISSUE THREAD

**Issue by jimmywarting** [Pandora-Protocol/pandora-protocol-reference#4]
https://github.com/Pandora-Protocol/pandora-protocol-reference/blob/d97aa8f18615f758c1a00baa80f145f1e4948368/src/pandora-locations/browser/browser-pandora-locations.js#L68

Are you absolutely sure that you calculate `pandoraBoxStream.size` it can't be the total sum of all the files... writing a zip will add a bunch of bytes... maybe better of to remove size altogether? 

---

Haven't tried this - only reviewing

**Comment by jimmywarting** [comment]
ups, my bad, you are only saving one stream that you know the size of... it's not a zip?

**Comment by ibudisteanu** [comment]
savePandoraBoxStreamAs is saving directly the stream as an array of chunks. No Zip included - pure binary stream . The function was tested and works perfectly thanks to your great library StreamSaver.js!

**Comment by jimmywarting** [comment]
Realized that afterwards
