### ISSUE TITLE
don't use async here?

### ISSUE THREAD

**Issue by jimmywarting** [Pandora-Protocol/pandora-protocol-reference#5]
https://github.com/Pandora-Protocol/pandora-protocol-reference/blob/d97aa8f18615f758c1a00baa80f145f1e4948368/src/pandora-locations/browser/browser-pandora-locations.js#L122

I don't see any huge benefits of doing this with async? maybe missing something
all you are basically doing is writing a bunch of object to conflux that works pretty fast.

You can write quite many file like directly to conflux without any memory problem.
the important part is that you have a stream function that return or resolves to a whatwg readable stream 

```js
// Example of a File like object
const domFileLike = {
  name: 'abc.txt',
  stream() {
    return new ReadableStream(...)
  }
}
```

Maybe do something like this:
```js
// returns a iterator
const iter = pandoraBox.streams.toArray().values()

new ReadableStream({
  // pull gets called when streamsaver ask for more data, works like this
  // - streamSaver: hey conflux, give me more data!
  // - conflux: uh? i don't have any data. I'm just a transform stream.
  // - conflux: wait a sec i pull data from the parent readableStream and then forwards it to you.
  async pull (ctrl) {
    const { value, done } = iter.next()
    if (done) return ctrl.close()

    // do something with value

    ctrl.enqueue(/* DomfileLike|Folder */)
  }
})
  .pipeThrough(new Writable())
  .pipeTo(streamSaver.createWriteStream('name.zip'))
```

**Comment by ibudisteanu** [comment]
You are totally right. I used async.each because I personally didn't understand the 2nd example (pipes2)

Thanks for this tip! I will do it right now, and check if it works! It might work, I think.

**Comment by ibudisteanu** [comment]
I did the code refactor. https://github.com/Pandora-Protocol/pandora-protocol-reference/commit/3e5750c43965413b61e582c4e0558967cbb4133f

But, I get the same error.

![image](https://user-images.githubusercontent.com/17750489/89088129-640c2600-d39f-11ea-8b57-3c7893543ec5.png)


I think, it might be an issue with webpack
