### ISSUE TITLE
You could possible avoid node streams altogether here:

### ISSUE THREAD

**Issue by jimmywarting** [Pandora-Protocol/pandora-protocol-reference#6]
Here is two issues
https://github.com/Pandora-Protocol/pandora-protocol-reference/blob/3e5750c43965413b61e582c4e0558967cbb4133f/src/pandora-locations/browser/browser-pandora-locations.js#L137-L145

137: it's a node stream and not a web stream
144: this is not how a File like object looks like... stream should be a function that returns a new web ReadableStream:

```js
 ctrl.enqueue({ 
     name: pandoraBoxStream.path, 
     lastModified: new Date(0), 
     stream() {
        return mystream
     }, 
 }); 
```

**Comment by jimmywarting** [comment]
If i understood all what your code is doing then maybe you can replace all of this:

https://github.com/Pandora-Protocol/pandora-protocol-reference/blob/3e5750c43965413b61e582c4e0558967cbb4133f/src/pandora-locations/browser/browser-pandora-locations.js#L121-L170

...node stuff with just javascript api:s and avoid the need of having to convert/pipe a node stream to a web stream by just using web streams directly instead

```js
const {chunksCount, absolutePath, chunkSize} = pandoraBoxStream
let i = 0

const mystream = new ReadableStream({
  start (ctrl) {
    // return a promise if you have to wait for something
    // or remove this altogether 
  },
  pull (ctrl) {
    return new Promise(resolve, reject => {
      this.getLocationStreamChunk(absolutePath, i, chunkSize, pandoraBoxStream.chunkRealSize(i), (err, buffer) => {
        if (err) return reject(err)
        if (stopped) return reject(new Error('stopped'))
        ctrl.enqueue(buffer)
        if (++i === chunksCount) ctrl.close() // done writing this file now
      })
    })
  },
  cancel() {
    // something cancel
    // user could have cancel from browser UI
    // You could remove this also...
  }
})

ctrl.enqueue({
    name: pandoraBoxStream.path,
    lastModified: new Date(0),
    stream () {
      // You could also move all of the above in here too.
      // (thought it created too much indentation)
      return mystream
    },
});
```

**Comment by ibudisteanu** [comment]
There is an array of pandoraBoxStreams.
Each PandoraBoxStream is made of multiple chunks, that's why I have that iterator
The code simply wants to create an zip including all pandora box streams (made of their chunks)

LE: you are right, I will integrate it now. Thanks for the support.

**Comment by jimmywarting** [comment]
> There is an array of pandoraBoxStreams.
> Each PandoraBoxStream is made of multiple chunks, that's why I have that iterator

Maybe i didn't grasp all of what your code is doing then...

> The code simply wants to create an zip including all pandora box streams (made of their chunks)

The above code will be executed for each pandoraBoxStreams if i did it correctly (but maybe not)

> LE: you are right, I will integrate it now. Thanks for the support.

So i maybe was right :)
Anyhow going to bed now, good luck to you.

(updated the above code just slightly)

**Comment by ibudisteanu** [comment]
I have updated it, but I encounter the same error described last time. 
https://github.com/Pandora-Protocol/pandora-protocol-reference/commit/ebf68d467b454ba8acca2874d74e164404ebc9d3

![image](https://user-images.githubusercontent.com/17750489/89089899-42fc0300-d3a8-11ea-8e47-0476bbb946ea.png)

I wish you a great sleep! Thanks for the help. I will search furthermore the incompatibility for the `.pipeThrough( new Writer() )` why is not working.

**Comment by ibudisteanu** [comment]
After testing on Firefox v79, I found that it returns me a different error message.

![image](https://user-images.githubusercontent.com/17750489/89090717-72613e80-d3ad-11ea-91bc-466b5e568a41.png)

**Comment by jimmywarting** [comment]
you probably need to have the same polyfilled web streams as conflux have all over the place for now to make it work

`npm i web-streams-polyfill@^2.1.0`

```js
import { WritableStream, ReadableStream, TransformStream } from 'web-streams-polyfill/ponyfill'
import streamSaver from 'streamsaver'
// change streamsaver WritableStream to be a polyfilled version instead
streamSaver.WritableStream = WritableStream
```

https://github.com/transcend-io/conflux/pull/47#issuecomment-667441740

**Comment by ibudisteanu** [comment]
hi @jimmywarting ! Thank you so much for the support. Indeed it solves the above errors.

I was able to make the saveAs working with your help! I will try to see if it works with 2-3-4 gb streams.

**Comment by ibudisteanu** [comment]
Feel free to close the issue
